import Sidebar from "@/components/main/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import Navbar from "@/components/main/Navbar";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import { ModalProvider } from "@/providers/modal-provider";
import Providers from "@/providers/session";

const inter = Inter({ subsets: ["latin"] });
const monsterrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <Providers>
      <body className={monsterrat.className}>
      <ModalProvider />
        <div className="flex">
          <Sidebar />
          <div className="w-full">
            <Navbar user={session?.user} />
            <div className="bg-slate-100 h-full p-16">{children}</div>
          </div>
        </div>
      </body>
      </Providers>
    </html>
  );
}
